apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    uid: product-memory-prometheus
    url: http://prometheus:9090
    isDefault: true
    jsonData:
      timeInterval: 15s

  - name: Loki
    type: loki
    access: proxy
    uid: product-memory-loki
    url: http://loki:3100

  - name: Product Memory Postgres
    type: postgres
    access: proxy
    uid: product-memory-postgres
    url: db:5432
    user: ${POSTGRES_USER}
    database: ${POSTGRES_DB}
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    jsonData:
      sslmode: disable
      postgresVersion: 1700
