import importlib.util
from pathlib import Path


def _load_script():
    script_path = Path(__file__).resolve().parents[1] / "scripts" / "link_knowledge.py"
    spec = importlib.util.spec_from_file_location("link_knowledge", script_path)
    assert spec and spec.loader
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def test_link_knowledge_creates_configured_symlinks(tmp_path: Path) -> None:
    script = _load_script()
    source = tmp_path / "Teams Transcripts"
    source.mkdir()
    (tmp_path / ".env").write_text(
        f"HOST_KNOWLEDGE_DIR=knowledge\nKNOWLEDGE_LINKED_DIRS=teams={source}\n",
        encoding="utf-8",
    )

    assert script.main(tmp_path) == 0

    link = tmp_path / "knowledge" / "teams"
    assert link.is_symlink()
    assert link.resolve() == source
    compose_file = tmp_path / "docker-compose.override.yml"
    assert compose_file.exists()
    assert f'source: "{source}"' in compose_file.read_text(encoding="utf-8")
    assert f'target: "{source}"' in compose_file.read_text(encoding="utf-8")


def test_link_knowledge_refuses_to_overwrite_real_directory(tmp_path: Path) -> None:
    script = _load_script()
    source = tmp_path / "source"
    source.mkdir()
    existing = tmp_path / "knowledge" / "teams"
    existing.mkdir(parents=True)
    (tmp_path / ".env").write_text(
        f"HOST_KNOWLEDGE_DIR=knowledge\nKNOWLEDGE_LINKED_DIRS=teams={source}\n",
        encoding="utf-8",
    )

    assert script.main(tmp_path) == 1
    assert existing.is_dir()
    assert not existing.is_symlink()


def test_link_knowledge_removes_generated_override_file_when_config_is_empty(tmp_path: Path) -> None:
    script = _load_script()
    compose_file = tmp_path / "docker-compose.override.yml"
    compose_file.write_text(
        "# Generated by make link-knowledge. Do not edit by hand.\nservices: {}\n",
        encoding="utf-8",
    )
    (tmp_path / ".env").write_text("KNOWLEDGE_LINKED_DIRS=\n", encoding="utf-8")

    assert script.main(tmp_path) == 0
    assert not compose_file.exists()


def test_link_knowledge_removes_legacy_generated_compose_file(tmp_path: Path) -> None:
    script = _load_script()
    source = tmp_path / "source"
    source.mkdir()
    legacy_file = tmp_path / "docker-compose.knowledge-links.yml"
    legacy_file.write_text(
        "# Generated by make link-knowledge. Do not edit by hand.\nservices: {}\n",
        encoding="utf-8",
    )
    (tmp_path / ".env").write_text(
        f"HOST_KNOWLEDGE_DIR=knowledge\nKNOWLEDGE_LINKED_DIRS=teams={source}\n",
        encoding="utf-8",
    )

    assert script.main(tmp_path) == 0
    assert not legacy_file.exists()
