from __future__ import annotations

import os
import sys
from json import dumps
from pathlib import Path

ENV_FILE = ".env"
LINKS_KEY = "KNOWLEDGE_LINKED_DIRS"
HOST_KNOWLEDGE_DIR_KEY = "HOST_KNOWLEDGE_DIR"
COMPOSE_LINKS_FILE = "docker-compose.knowledge-links.yml"
GENERATED_MARKER = "# Generated by make link-knowledge. Do not edit by hand."


def main(repo_root: Path | None = None) -> int:
    repo_root = repo_root or Path(__file__).resolve().parents[1]
    config = _read_env_file(repo_root / ENV_FILE)
    knowledge_dir = _resolve_path(config.get(HOST_KNOWLEDGE_DIR_KEY, "./knowledge"), repo_root)
    try:
        entries = _parse_entries(config.get(LINKS_KEY, ""))
    except ValueError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1

    knowledge_dir.mkdir(parents=True, exist_ok=True)
    if not entries:
        try:
            _remove_generated_compose_file(repo_root / COMPOSE_LINKS_FILE)
        except RuntimeError as exc:
            print(f"error: {exc}", file=sys.stderr)
            return 1
        print(f"{LINKS_KEY} is empty; no knowledge folders to link.")
        return 0

    linked = unchanged = replaced = 0
    source_paths: list[Path] = []
    for name, source in entries:
        source_path = _resolve_path(source, repo_root)
        if not source_path.is_dir():
            print(f"error: {source_path} is not a directory", file=sys.stderr)
            return 1
        source_paths.append(source_path)

        link_path = knowledge_dir / name
        if link_path.exists() or link_path.is_symlink():
            if not link_path.is_symlink():
                print(f"error: {link_path} already exists and is not a symlink", file=sys.stderr)
                return 1
            if link_path.resolve() == source_path.resolve():
                unchanged += 1
                continue
            link_path.unlink()
            replaced += 1

        link_path.symlink_to(source_path, target_is_directory=True)
        linked += 1

    try:
        _write_compose_links(repo_root / COMPOSE_LINKS_FILE, source_paths)
    except RuntimeError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1
    print(
        f"Knowledge links ready in {knowledge_dir}: "
        f"{linked} created, {replaced} replaced, {unchanged} unchanged."
    )
    return 0


def _read_env_file(path: Path) -> dict[str, str]:
    if not path.exists():
        return {}

    values: dict[str, str] = {}
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        values[key.strip()] = _strip_quotes(value.strip())
    return values


def _strip_quotes(value: str) -> str:
    if len(value) >= 2 and value[0] == value[-1] and value[0] in {"'", '"'}:
        return value[1:-1]
    return value


def _parse_entries(raw_value: str) -> list[tuple[str, str]]:
    entries: list[tuple[str, str]] = []
    for raw_entry in raw_value.split(";"):
        entry = raw_entry.strip()
        if not entry:
            continue

        if "=" in entry:
            name, source = entry.split("=", 1)
            name = name.strip()
            source = source.strip()
        else:
            source = entry
            name = Path(source).expanduser().name

        _validate_link_name(name)
        entries.append((name, _strip_quotes(source)))
    return entries


def _validate_link_name(name: str) -> None:
    if not name or name in {".", ".."} or "/" in name or "\\" in name or name.startswith("."):
        raise ValueError(f"Invalid knowledge link name: {name!r}")


def _resolve_path(value: str, repo_root: Path) -> Path:
    path = Path(os.path.expandvars(value)).expanduser()
    if not path.is_absolute():
        path = repo_root / path
    return path


def _write_compose_links(path: Path, source_paths: list[Path]) -> None:
    _ensure_generated_or_missing(path)
    unique_sources = sorted({source.resolve() for source in source_paths})
    lines = [
        GENERATED_MARKER,
        "services:",
        "  product-memory:",
        "    volumes:",
    ]
    for source in unique_sources:
        quoted_source = dumps(str(source))
        lines.extend(
            [
                "      - type: bind",
                f"        source: {quoted_source}",
                f"        target: {quoted_source}",
                "        read_only: true",
            ]
        )
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _remove_generated_compose_file(path: Path) -> None:
    if not path.exists():
        return
    _ensure_generated_or_missing(path)
    path.unlink()


def _ensure_generated_or_missing(path: Path) -> None:
    if not path.exists():
        return
    lines = path.read_text(encoding="utf-8").splitlines()
    first_line = lines[0] if lines else ""
    if first_line != GENERATED_MARKER:
        raise RuntimeError(f"{path} exists but was not generated by make link-knowledge")


if __name__ == "__main__":
    raise SystemExit(main())
